import { createClient } from '@supabase/supabase-js';
import './review.css';
const SB_URL='https://zngncasvdrrxyrkjqutj.supabase.co',SB_KEY='sb_publishable_wUrH6t12z4tRKruS28LqWQ_2GG06U9m',sb=createClient(SB_URL,SB_KEY),app=document.querySelector('#app');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let items=[],filter='needs';
const hasCoord=x=>Number.isFinite(Number(x.latitude))&&Number.isFinite(Number(x.longitude));
const state=x=>{if(!hasCoord(x))return 'red';if(x.verified)return 'green';if(x.osm_match_status==='matched'||x.wikidata_match_status==='matched'||x.coordinate_status==='verified')return 'green';return 'yellow'};
async function load(){const {data:{session}}=await sb.auth.getSession();if(!session?.user){app.innerHTML='<section class="empty"><h1>Sign in to Travelite first.</h1><a href="./">Open Travelite</a></section>';return}const {data,error}=await sb.from('places').select('id,name,name_japanese,city,area,place_type,latitude,longitude,verified,coordinate_source,coordinate_status,osm_match_status,osm_distance_m,wikidata_match_status,wikidata_distance_m,prominence,visit_behavior,estimated_minutes_min,estimated_minutes_max').eq('status','active').in('city',['Kyoto','Nagaokakyo']).order('area').order('name');if(error){app.innerHTML='<section class="empty"><h1>Could not load Kyoto POIs.</h1><p>'+esc(error.message)+'</p></section>';return}items=data||[];render()}
function render(){const counts={green:0,yellow:0,red:0};items.forEach(x=>counts[state(x)]++);const shown=items.filter(x=>filter==='all'||(filter==='needs'?state(x)!=='green':state(x)===filter));app.innerHTML=`<header><a class="brand" href="./">◉ travelite<span>.</span></a><a class="back" href="./review.html">Photo review</a></header><section class="intro"><p>KYOTO POI REVIEW</p><h1>Kyoto coordinates & POI checks.</h1><div class="stats"><button data-filter="needs">Needs review ${counts.yellow+counts.red}</button><button data-filter="green">Green ${counts.green}</button><button data-filter="yellow">Yellow ${counts.yellow}</button><button data-filter="red">Red ${counts.red}</button><button data-filter="all">All ${items.length}</button></div></section><main class="photo-grid">${shown.map(x=>{const s=state(x),dist=x.osm_distance_m??x.wikidata_distance_m;return `<article class="photo-card poi-${s}"><div class="photo-info"><p class="label">${s.toUpperCase()} · ${esc(x.area||x.city)}</p><h2>${esc(x.name)}</h2><p>${esc([x.place_type,x.prominence,x.visit_behavior].filter(Boolean).join(' · '))}</p><p>${hasCoord(x)?esc(Number(x.latitude).toFixed(6)+', '+Number(x.longitude).toFixed(6)):'Missing coordinates'}</p><p>${dist!=null?'Match distance: '+Math.round(dist)+' m':''}</p><div class="actions"><button data-action="verify" data-id="${x.id}">Verify</button><button data-action="delete" data-id="${x.id}">Delete</button></div></div></article>`}).join('')||'<section class="empty"><h2>Nothing in this filter.</h2></section>'}</main>`}
document.addEventListener('click',async e=>{const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;render();return}const b=e.target.closest('[data-action]');if(!b)return;const id=Number(b.dataset.id),row=items.find(x=>x.id===id);if(!row)return;if(b.dataset.action==='verify'){if(!hasCoord(row)){alert('This POI still needs coordinates before it can be verified.');return}const {error}=await sb.from('places').update({verified:true,coordinate_status:'verified'}).eq('id',id);if(error)alert(error.message);else load()}if(b.dataset.action==='delete'){if(!confirm('Delete '+row.name+' from public.places?'))return;const {error}=await sb.from('places').delete().eq('id',id);if(error)alert(error.message);else load()}});
load();