create table if not exists public.place_planning_profiles (
  place_id bigint primary key references public.places(id) on delete cascade,
  typical_duration_min integer not null default 60 check (typical_duration_min > 0),
  minimum_useful_time_min integer not null default 30 check (minimum_useful_time_min > 0),
  importance smallint not null default 50 check (importance between 0 and 100),
  detour_worthiness smallint not null default 50 check (detour_worthiness between 0 and 100),
  filler_score smallint not null default 50 check (filler_score between 0 and 100),
  time_sensitivity smallint not null default 0 check (time_sensitivity between 0 and 100),
  crowd_sensitivity smallint not null default 0 check (crowd_sensitivity between 0 and 100),
  area_cluster text,
  pairing_group text,
  anchor_place boolean not null default false,
  move_to_another_day boolean not null default false,
  scheduling_notes text,
  updated_at timestamptz not null default now()
);

create table if not exists public.place_time_windows (
  id bigint generated by default as identity primary key,
  place_id bigint not null references public.places(id) on delete cascade,
  label text not null,
  window_kind text not null default 'clock' check (window_kind in ('clock','sunrise','sunset','opening','closing')),
  start_time time,
  end_time time,
  start_offset_min integer not null default 0,
  end_offset_min integer not null default 0,
  experience_score smallint not null default 70 check (experience_score between 0 and 100),
  crowd_score smallint not null default 50 check (crowd_score between 0 and 100),
  strength text not null default 'preferred' check (strength in ('ideal','strong','preferred','acceptable','avoid')),
  reason text,
  priority smallint not null default 50 check (priority between 0 and 100),
  created_at timestamptz not null default now(),
  check ((window_kind='clock' and start_time is not null and end_time is not null) or window_kind <> 'clock')
);

create index if not exists place_time_windows_place_id_idx on public.place_time_windows(place_id);
create index if not exists place_planning_profiles_cluster_idx on public.place_planning_profiles(area_cluster);

alter table public.place_planning_profiles enable row level security;
alter table public.place_time_windows enable row level security;

drop policy if exists "planning profiles readable" on public.place_planning_profiles;
create policy "planning profiles readable" on public.place_planning_profiles for select to authenticated using (true);
drop policy if exists "time windows readable" on public.place_time_windows;
create policy "time windows readable" on public.place_time_windows for select to authenticated using (true);
