create table if not exists public.trip_places (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  place_id bigint not null references public.places(id) on delete cascade,
  notes text,
  created_at timestamptz not null default now(),
  unique (trip_id, place_id)
);
alter table public.trip_places enable row level security;
create policy "Read accessible trip places" on public.trip_places for select to authenticated using (public.is_trip_owner(trip_id) or public.is_trip_member(trip_id));
create policy "Editors add trip places" on public.trip_places for insert to authenticated with check (public.is_trip_owner(trip_id) or public.is_trip_editor(trip_id));
create policy "Editors remove trip places" on public.trip_places for delete to authenticated using (public.is_trip_owner(trip_id) or public.is_trip_editor(trip_id));
grant select, insert, delete on public.trip_places to authenticated;
grant usage, select on sequence public.trip_places_id_seq to authenticated;
