-- Travelite product boundary: user pins first, curated day trips only when there is slack.
-- A destination already present as a trip base must be suppressed by the UI.
-- A destination already represented in the user's pile must also be suppressed.
create table if not exists public.trip_bases (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  city text not null, country text,
  start_date date, end_date date,
  nights integer check (nights is null or nights >= 0),
  hotel_area text, sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (trip_id, city, start_date)
);
create table if not exists public.day_trip_suggestions (
  id bigint generated by default as identity primary key,
  base_city text not null, base_country text not null default 'Japan',
  destination_city text not null, destination_country text not null default 'Japan',
  commitment text not null check (commitment in ('half','full','raid','full_or_raid','half_or_full','long_full')),
  why text not null, headline text, sort_order integer not null default 0,
  active boolean not null default true, created_at timestamptz not null default now(),
  unique (base_city, base_country, destination_city, destination_country)
);
create index if not exists trip_bases_trip_id_idx on public.trip_bases(trip_id);
create index if not exists day_trip_suggestions_base_idx on public.day_trip_suggestions(base_country,base_city,active);
alter table public.trip_bases enable row level security;
alter table public.day_trip_suggestions enable row level security;
drop policy if exists "trip bases readable by members" on public.trip_bases;
create policy "trip bases readable by members" on public.trip_bases for select to authenticated using (
  exists (select 1 from public.trips t where t.id=trip_bases.trip_id and t.owner_id=auth.uid())
  or exists (select 1 from public.trip_members tm where tm.trip_id=trip_bases.trip_id and tm.user_id=auth.uid())
);
drop policy if exists "trip bases writable by owner" on public.trip_bases;
create policy "trip bases writable by owner" on public.trip_bases for all to authenticated using (
  exists (select 1 from public.trips t where t.id=trip_bases.trip_id and t.owner_id=auth.uid())
) with check (
  exists (select 1 from public.trips t where t.id=trip_bases.trip_id and t.owner_id=auth.uid())
);
drop policy if exists "day trips readable" on public.day_trip_suggestions;
create policy "day trips readable" on public.day_trip_suggestions for select to authenticated using (true);
insert into public.day_trip_suggestions(base_city,destination_city,commitment,why,headline,sort_order) values
('Kyoto','Uji','half','Matcha, tea culture and Byodo-in.','An easy half-day change of pace.',10),
('Kyoto','Nara','full_or_raid','Deer, major temples and Mt. Wakakusa around sunset.','Nature, temples and sunset.',20),
('Kyoto','Osaka','full','Food, city energy and an evening in Osaka.','Trade a Kyoto day for a city day.',30),
('Kyoto','Ine','long_full','Funaya boathouses, coastline and sea views.','A long coastal day out.',40),
('Osaka','Nara','full_or_raid','Deer, major temples and Mt. Wakakusa around sunset.','Nature, temples and sunset.',10),
('Osaka','Kobe','half_or_full','Harbour city atmosphere with an easy change of pace from Osaka.','A nearby harbour-city escape.',20),
('Osaka','Kyoto','full','Historic neighbourhoods, temples and a very different city rhythm.','Trade an Osaka day for Kyoto.',30),
('Osaka','Himeji','half_or_full','Himeji Castle and a focused historic outing.','A castle-led day out.',40)
on conflict (base_city,base_country,destination_city,destination_country) do update set commitment=excluded.commitment,why=excluded.why,headline=excluded.headline,sort_order=excluded.sort_order,active=true;