-- Planner transport/state tables. Mirrors the live production schema so Git is the source of truth.
create table if not exists public.destinations (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  country text not null default 'Japan',
  prefecture text,
  destination_type text not null default 'city',
  description_short text,
  identity_tags text[] not null default '{}',
  experience_types text[] not null default '{}',
  character_tags text[] not null default '{}',
  latitude double precision,
  longitude double precision,
  parent_destination_id bigint references public.destinations(id) on delete set null,
  status text not null default 'active',
  intelligence_source text,
  intelligence_confidence text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.destination_transport_anchors (
  id bigint generated by default as identity primary key,
  destination_id bigint not null references public.destinations(id) on delete cascade,
  name text not null, anchor_type text not null default 'rail', anchor_role text not null default 'primary',
  latitude double precision not null, longitude double precision not null, priority integer not null default 1,
  active boolean not null default true, source text, source_id text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.destination_travel_estimates (
  id bigint generated by default as identity primary key,
  from_anchor_id bigint not null references public.destination_transport_anchors(id) on delete cascade,
  to_anchor_id bigint not null references public.destination_transport_anchors(id) on delete cascade,
  mode text not null default 'rail', typical_minutes integer not null, min_minutes integer, max_minutes integer, transfers integer,
  source text not null default 'curated', confidence text not null default 'medium', active boolean not null default true,
  checked_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(from_anchor_id,to_anchor_id,mode)
);
create table if not exists public.trip_planning_state (
  trip_id bigint primary key references public.trips(id) on delete cascade,
  trip_days integer not null default 0 check(trip_days>=0), scene_count integer not null default 0 check(scene_count>=0),
  coverage_status text not null default 'unknown' check(coverage_status in ('unknown','under_specified','balanced','over_specified')),
  under_specified_choice text check(under_specified_choice is null or under_specified_choice in ('add_scene','free_day','keep_loose')),
  pace_preference text not null default 'balanced' check(pace_preference in ('chill','balanced','packed')),
  crowd_preference text not null default 'balanced' check(crowd_preference in ('avoid','balanced','timing')),
  updated_at timestamptz not null default now()
);
alter table public.destinations enable row level security;
alter table public.destination_transport_anchors enable row level security;
alter table public.destination_travel_estimates enable row level security;
alter table public.trip_planning_state enable row level security;
drop policy if exists "destinations readable" on public.destinations;
create policy "destinations readable" on public.destinations for select to authenticated using(true);
drop policy if exists "transport anchors readable" on public.destination_transport_anchors;
create policy "transport anchors readable" on public.destination_transport_anchors for select to authenticated using(true);
drop policy if exists "travel estimates readable" on public.destination_travel_estimates;
create policy "travel estimates readable" on public.destination_travel_estimates for select to authenticated using(true);
drop policy if exists "trip planning state owner access" on public.trip_planning_state;
create policy "trip planning state owner access" on public.trip_planning_state for all using(exists(select 1 from public.trips t where t.id=trip_id and t.owner_id=auth.uid())) with check(exists(select 1 from public.trips t where t.id=trip_id and t.owner_id=auth.uid()));
